# Jekyll Configuration for Team 60855 Gearshift
# ================================================

# Site Settings
title: "Team 60855 Gearshift"
email: team60855@gearshift.fll
description: A passionate FLL robotics team competing in FIRST LEGO League 2025-2026
timezone: UTC
baseurl: "/team-gearshift"
url: "https://harsh29.github.io"
permalink: "/:title/"
logo: 'assets/images/gearshift-logo.png'
favicon: 'assets/images/favicon.ico'
locale: en_us
lang: en_us

# Team Information
team:
  number: "60855"
  name: "Gearshift"
  season: "2025-2026"
  location: "Your School/Location"
  email: "team60855@gearshift.fll"

# Pagination
paginate: 30

# Feed Settings
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

# Markdown Settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: true

# Sass Settings
sass:
  sass_dir: _sass
  style: :compressed

# Authors
authors:
  team-gearshift:
    name: Team Gearshift
    display_name: Team 60855 Gearshift
    avatar: 'assets/images/gearshift-logo.png'
    email: team60855@gearshift.fll
    web: https://harsh29.github.io/team-gearshift/
    description: "Team 60855 Gearshift - A passionate FLL robotics team competing in FIRST LEGO League 2025-2026 season."

# Social Media (Update with your actual links)
social:
  instagram: https://www.instagram.com/teamgearshift/
  facebook: https://www.facebook.com/teamgearshift/
  twitter: https://twitter.com/teamgearshift/

# Build Settings - Remove theme line since we're using local theme files
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Collections for Blog Posts
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: team-gearshift

# Exclude from processing
exclude:
  - README.md
  - QUICKSTART.md
  - PROJECT_SUMMARY.md
  - HOSTING_INSTRUCTIONS.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
